name: Publish Check My Repo

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Gives access to repository
      - name: Workflow access
        uses: actions/checkout@v2
      # Add node
      - name: Setup Node version
        uses: actions/setup-node@v1
        with:
          node-version: '12'


      # Install dependencies
      - name: Install dependencies
        run: npm install

       # Which file to act upon
      - name: Build site assets
        working-directory: ${{ github.workspace }}
        run: ls -la

      - name: Install dependencies
        working-directory: frontend
        run: |
          npm install

      - name: Build
        working-directory: frontend
        run: |
          npm run build

      - name: Deploy
        working-directory: frontend
        run: |
          npm run deploy
