name: Deploy to GitHub Pages

on:
  workflow_run:
    # workflows: ["Verify Repo Health Daily", "Lint And Deploy On Push To Main"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Gives access to repository
        uses: actions/checkout@v2
      - name: Setup Node version
        uses: actions/setup-node@v1
        with:
          node-version: '12'

      - name: Install Frontend
        run: cd frontend && npm install

      - name: Copy artifact to frontend
        uses: actions/download-artifact@v2
        with:
          name: frontend-json
          path: ./frontend/public

      - name: Build Vue
        run: cd frontend && npm run build

      - name: Deploy Vue Site
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend/dist
          publish_branch: gh-pages
          user_name: 'OSS Sauce Bot'
          user_email: 'oss-sauce-bot@users.noreply.github.com'
          commit_message: ${{ github.event.head_commit.message }}
