name: Publish Check My Repo

on:
  push:
    branches:
      - main

env:
  GITHUB_TOKEN: ${{GITHUB_TOKEN}}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Add node
      - name: Setup Node version
        uses: actions/setup-node@v1
        with:
          node-version: '12'

      # Add a project to work on
      - name: Clone Repository
        uses: actions/checkout@v2

      # Install dependencies
      - name: Install dependencies
        run: npm install

       # Which file to act upon
       - name: Frontend
        working-directory: frontend

      # Install frontend dependencies
      - name: Install dependencies
        run: npm install

      # Run deployment script
      - name: Deploy
        run: npm run deploy
