name: Publish Check My Repo

on:
  push:
    branches:
      - main

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  repository: ${{github.repository}}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Gives access to repository
      - name: Workflow access
        uses: actions/checkout@v2
      # Add node
      - name: Setup Node version
        uses: actions/setup-node@v1
        with:
          node-version: '12'
          repository: ${{github.repository}}
          user_name: 'OSS Sauce Bot'
          user_email: 'oss-sauce-bot@users.noreply.github.com'

      # Install dependencies
      - name: Install dependencies
        run: npm install

       # Which file to act upon
      - name: Build site assets
        working-directory: ${{ github.workspace }}
        run: ls -la

      - name: Install dependencies
        working-directory: frontend
        run: |
          npm install

      - name: Build
        working-directory: frontend
        run: |
          npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: dist # The folder the action should deploy.
          CLEAN: true


