name: Deploy Frontend On Push To Main

on:
  push:
    branches:
      - main

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Gives access to repository
      - name: Workflow access
        uses: actions/checkout@v2
      # Add node
      - name: Setup Node version
        uses: actions/setup-node@v1
        with:
          node-version: '12'

      - name: Deploy Site
        uses: ./.github/actions/deploy
