name: Publish Check My Repo

on:
  push:
    branches:
      - main

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  repository: ${{github.repository}}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Gives access to repository
      - name: Workflow access
        uses: actions/checkout@v2
      # Add node
      - name: Setup Node version
        uses: actions/setup-node@v1
        with:
          node-version: '12'

      # Install dependencies
      - name: Install dependencies
        run: npm install

       # Which file to act upon
      - name: Build site assets
        defaults:
          run:
            working-directory: frontend

        - name: Install dependencies
          run: |
            npm install

        - name: Build
          run: |
            npm run build

        - name: Deploy
          run: |
            npm run deploy

        - name: Commit changes
          uses: EndBug/add-and-commit@v6
          with:
            author_name: 'OSS Sauce Bot'
            author_email: oss-sauce-bot@users.noreply.github.com
            message: 'deploy'
            add: -A

