name: Run tests on every commit

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Add node
      - name: Setup Node version
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      # Add a project to work on
      - name: Clone Repository
        uses: actions/checkout@v3

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Which file to act upon
      - name: Run tests
        run: npm test
