name: Lint And Deploy On Push To Main

on:
  push:

jobs:
  Lint-Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Gives access to repository
        uses: actions/checkout@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Node version
        uses: actions/setup-node@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          node-version: '12'

      - name: Install dependencies
        run: npm install

      - name: Generate frontened data
        run: node src/index.js

      - name: Install Frontend
        run: cd frontend && npm install

